name         'thomasvandoren-redis'
version      '0.10.0'
summary      'Install and configure redis.'
description  'Install and configure redis.'
author       'Thomas Van Doren'
license      'BSD'
project_page 'https://github.com/thomasvandoren/puppet-redis'
dependency   'maestrodev/wget', '>= 1.1.0'
dependency   'puppetlabs/gcc', '>= 0.0.3'
